CREATE DATABASE IF NOT EXISTS Purbeurre CHARACTER SET 'utf8';

USE Purbeurre;

CREATE TABLE Food(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name_food VARCHAR(50) NOT NULL,
nutriscore VARCHAR(3) NOT NULL,
description VARCHAR(1000),
store VARCHAR(100),
link VARCHAR(300)
);

CREATE TABLE Favorite(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
id_food INT UNSIGNED NOT NULL,
substitute_chooses VARCHAR(50) NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE Category(
id INT UNSIGNED AUTO_INCREMENT NOT NULL UNIQUE,
categories VARCHAR(50)
);

ALTER TABLE Category
ADD PRIMARY KEY (categories);

ALTER TABLE Food
ADD INDEX ind_nutriscore (nutriscore);

ALTER TABLE Favorite
ADD CONSTRAINT fk_favorite_id_food FOREIGN KEY (id_food) REFERENCES Food (id);
